# -*- coding: utf-8 -*-
"""KDD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c82vVKaenEDTYtVgqrX5dlqGTqsUurbh

#KDD

#1. Selection
"""

# Import required libraries
import zipfile
import os
import pandas as pd

# Define file path (assuming it's uploaded to Colab)
from google.colab import files
# uploaded = files.upload()

# # Unzip the file
# zip_file = 'UNSW-NB15.zip'  # Replace with your actual filename
# with zipfile.ZipFile(zip_file, 'r') as zip_ref:
#     zip_ref.extractall('/content/unsw_nb15')

# Check the extracted files
os.listdir('/content/unsw_nb15')

# Load the dataset
data_file = '/content/unsw_nb15/UNSW_NB15_training-set.csv'  # Adjust the path if necessary
df = pd.read_csv(data_file)

# Preview the dataset
df.head()

#Understanding the Data
# Basic data information
df.info()

# Display basic statistics
df.describe()

"""#2. Preprocessing (Data Cleaning)

"""

print(df.columns)

# Strip whitespace and ensure the column exists
df.columns = df.columns.str.strip()
print(df.columns)

if 'protocol' in df.columns:
    df['protocol'].fillna(df['protocol'].mode()[0], inplace=True)
else:
    print("'protocol' column is not present in the dataset")

for col in df.columns:
    if df[col].dtype == 'object':  # For categorical columns
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:  # For numeric columns
        df[col].fillna(df[col].mean(), inplace=True)

"""#3. Transformation (Feature Engineering)"""

# Strip whitespace and ensure the column exists
df.columns = df.columns.str.strip()

# Check if the columns exist in the DataFrame
if 'src_ip' in df.columns and 'dst_ip' in df.columns:
    df = df.drop(columns=['src_ip', 'dst_ip'], axis=1)
    print("Columns 'src_ip' and 'dst_ip' dropped successfully.")
else:
    missing_columns = [col for col in ['src_ip', 'dst_ip'] if col not in df.columns]
    print(f"Columns not found in DataFrame: {missing_columns}")

    # Print all columns to help identify potential typos
    print("Available columns:", df.columns)

"""#4. Data Mining (Model Building)"""

# Print all column names
print(df.columns)

# Encoding the 'proto' column
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
le = LabelEncoder()

# Apply Label Encoding to the 'proto' column
df['proto'] = le.fit_transform(df['proto'])

# Check the transformation
print(df['proto'].head())

categorical_columns = ['proto', 'service', 'state']  # Add any other categorical columns

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

from sklearn.model_selection import train_test_split

# Define the feature set (X) and the target (y)
X = df.drop(['label', 'attack_cat'], axis=1)  # Drop the target columns
y = df['label']  # The label column is your target (0: normal, 1: attack)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Training set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

# 1. HANDLE LABELS (The Fix)
# If your labels are strings (e.g., 'DoS', 'Normal'), we must encode them to 0, 1, 2...
# If they are already numbers but causing an error, we force them to integers.
if y_train.dtype == 'object' or str(y_train.dtype).startswith('str'):
    le = LabelEncoder()
    y_train = le.fit_transform(y_train)
    y_test = le.transform(y_test)
    print("Encoded string labels to integers.")
else:
    # Force to integer in case they are floats (e.g., 1.0, 2.0)
    y_train = y_train.astype(int)
    y_test = y_test.astype(int)
    print("Converted continuous/float labels to integers.")

# 2. INITIALIZE MODEL
# Using 100 trees. n_jobs=-1 uses all your CPU cores to speed up training.
model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

# 3. TRAIN THE MODEL
print("Starting training... please wait.")
model.fit(X_train, y_train)

# 4. VERIFY
print("✅ Training complete!")
print(f"Classes found by model: {model.classes_}")

from sklearn.metrics import classification_report, accuracy_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model performance
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

# ROC-AUC score
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print(f"ROC-AUC Score: {roc_auc:.4f}")

# Plot ROC curve
fpr, tpr, thresholds = roc_curve(y_test, model.predict_proba(X_test)[:, 1])
plt.figure()
plt.plot(fpr, tpr, label=f"ROC curve (area = {roc_auc:.2f})")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend(loc="lower right")
plt.show()

# Import numpy for array manipulation
import numpy as np

# Feature importance
importances = model.feature_importances_
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")
for i in range(X_train.shape[1]):
    print(f"{i + 1}. Feature {X_train.columns[indices[i]]} ({importances[indices[i]]})")

import joblib

# Save the trained Random Forest model
joblib.dump(model, 'network_intrusion_detection_model.pkl')

# To load the model later (if needed)
loaded_model = joblib.load('network_intrusion_detection_model.pkl')

import joblib
import json
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# 1. SAVE THE MODEL
model_filename = 'random_forest_multi_model.pkl'
joblib.dump(model, model_filename)
print(f"✅ Model saved as: {model_filename}")

# 2. GENERATE THE DYNAMIC REPORT
# All possible labels in the original dataset
full_attack_names = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers',
                     'Generic', 'Normal', 'Reconnaissance', 'Worms']

# Find which unique classes actually exist in your test data (e.g., [0, 1])
unique_classes = np.unique(np.concatenate([y_test, model.predict(X_test)]))
unique_classes = sorted(unique_classes.astype(int))

# Filter the names list to match only the classes that exist in y_test
present_names = [full_attack_names[i] for i in unique_classes]

y_pred = model.predict(X_test)

# We use the filtered 'present_names' to avoid the "Size Mismatch" error
report = classification_report(y_test, y_pred, target_names=present_names)

with open('model_performance_report.txt', 'w') as f:
    f.write("====================================================\n")
    f.write("UNSW-NB15 MULTI-CLASS DETECTION REPORT\n")
    f.write("====================================================\n\n")
    f.write(report)

print("✅ Performance report saved as: model_performance_report.txt")

# 3. SAVE THE VISUAL CONFUSION MATRIX
plt.figure(figsize=(12, 8))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=present_names, yticklabels=present_names)
plt.title('Attack Detection - Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('confusion_matrix.png')
print("✅ Visual Confusion Matrix saved as: confusion_matrix.png")

# 4. SAVE CLASS MAPPING (The full dictionary for your AI Agent)
mapping = {i: name for i, name in enumerate(full_attack_names)}
with open('class_mapping.json', 'w') as f:
    json.dump(mapping, f)
print("✅ Class mapping saved as: class_mapping.json")

# 5. GOOGLE COLAB DOWNLOAD
try:
    from google.colab import files
    for f in [model_filename, 'model_performance_report.txt', 'confusion_matrix.png', 'class_mapping.json']:
        files.download(f)
    print("🚀 Downloading all files...")
except ImportError:
    print("Note: Manual download required if not on Google Colab.")
